artifact_uri: file:///C:/CMU%20Projects/Operationalizing%20AI/rt_crypto_volatility/mlruns/875896030304522619/9862211f287c4379b6425754d0e97967/artifacts
end_time: 1763562655164
entry_point_name: ''
experiment_id: '875896030304522619'
lifecycle_stage: active
run_id: 9862211f287c4379b6425754d0e97967
run_name: lr_tune_3
source_name: ''
source_type: 4
source_version: ''
start_time: 1763562655152
status: 3
tags: []
user_id: redsk
