artifact_uri: file:///C:/CMU%20Projects/Operationalizing%20AI/rt_crypto_volatility/mlruns/960079160078124089/d9fccbdc80cf4f8da3596cbfe79e62d8/artifacts
end_time: 1763512351388
entry_point_name: ''
experiment_id: '960079160078124089'
lifecycle_stage: active
run_id: d9fccbdc80cf4f8da3596cbfe79e62d8
run_name: logistic_regression
source_name: ''
source_type: 4
source_version: ''
start_time: 1763512346629
status: 3
tags: []
user_id: redsk
