artifact_uri: file:///C:/CMU%20Projects/Operationalizing%20AI/rt_crypto_volatility/mlruns/960079160078124089/77e44dca77584bfcad11342d8279b2d0/artifacts
end_time: 1763512235782
entry_point_name: ''
experiment_id: '960079160078124089'
lifecycle_stage: active
run_id: 77e44dca77584bfcad11342d8279b2d0
run_name: xgboost
source_name: ''
source_type: 4
source_version: ''
start_time: 1763512232881
status: 3
tags: []
user_id: redsk
