artifact_uri: file:///C:/CMU%20Projects/Operationalizing%20AI/rt_crypto_volatility/mlruns/960079160078124089/16a09cf0512c4f41abd7325ab71672e3/artifacts
end_time: 1763497990200
entry_point_name: ''
experiment_id: '960079160078124089'
lifecycle_stage: active
run_id: 16a09cf0512c4f41abd7325ab71672e3
run_name: logistic_regression
source_name: ''
source_type: 4
source_version: ''
start_time: 1763497963867
status: 3
tags: []
user_id: redsk
