artifact_uri: file:///C:/CMU%20Projects/Operationalizing%20AI/rt_crypto_volatility/mlruns/960079160078124089/be1440ec0d1f42d1bd71ab640816c491/artifacts
end_time: 1763512584224
entry_point_name: ''
experiment_id: '960079160078124089'
lifecycle_stage: active
run_id: be1440ec0d1f42d1bd71ab640816c491
run_name: xgboost
source_name: ''
source_type: 4
source_version: ''
start_time: 1763512581400
status: 3
tags: []
user_id: redsk
