artifact_uri: file:///C:/CMU%20Projects/Operationalizing%20AI/rt_crypto_volatility/mlruns/960079160078124089/f6c73dad757a4dabb39dc694a136c5ae/artifacts
end_time: 1763503075628
entry_point_name: ''
experiment_id: '960079160078124089'
lifecycle_stage: active
run_id: f6c73dad757a4dabb39dc694a136c5ae
run_name: logistic_regression
source_name: ''
source_type: 4
source_version: ''
start_time: 1763503071281
status: 3
tags: []
user_id: redsk
