artifact_uri: file:///C:/CMU%20Projects/Operationalizing%20AI/rt_crypto_volatility/mlruns/875896030304522619/1045a539a0a849afb1d9b93979edf123/artifacts
end_time: 1763562655226
entry_point_name: ''
experiment_id: '875896030304522619'
lifecycle_stage: active
run_id: 1045a539a0a849afb1d9b93979edf123
run_name: lr_tune_7
source_name: ''
source_type: 4
source_version: ''
start_time: 1763562655205
status: 3
tags: []
user_id: redsk
