artifact_uri: file:///C:/CMU%20Projects/Operationalizing%20AI/rt_crypto_volatility/mlruns/960079160078124089/62ed1ddfc7c3401b8faa451a1102028c/artifacts
end_time: 1763499770329
entry_point_name: ''
experiment_id: '960079160078124089'
lifecycle_stage: active
run_id: 62ed1ddfc7c3401b8faa451a1102028c
run_name: xgboost
source_name: ''
source_type: 4
source_version: ''
start_time: 1763499763762
status: 3
tags: []
user_id: redsk
