artifact_uri: file:///C:/CMU%20Projects/Operationalizing%20AI/rt_crypto_volatility/mlruns/960079160078124089/d99cf95336824b2f9093f2a2255d96c6/artifacts
end_time: 1763497550812
entry_point_name: ''
experiment_id: '960079160078124089'
lifecycle_stage: active
run_id: d99cf95336824b2f9093f2a2255d96c6
run_name: baseline_zscore
source_name: ''
source_type: 4
source_version: ''
start_time: 1763497550567
status: 3
tags: []
user_id: redsk
