artifact_uri: file:///C:/CMU%20Projects/Operationalizing%20AI/rt_crypto_volatility/mlruns/960079160078124089/26486bb8c78e46648dc7e0a72e6a9dca/artifacts
end_time: 1763500405146
entry_point_name: ''
experiment_id: '960079160078124089'
lifecycle_stage: active
run_id: 26486bb8c78e46648dc7e0a72e6a9dca
run_name: baseline_zscore
source_name: ''
source_type: 4
source_version: ''
start_time: 1763500404908
status: 3
tags: []
user_id: redsk
