artifact_uri: file:///C:/CMU%20Projects/Operationalizing%20AI/rt_crypto_volatility/mlruns/960079160078124089/bd66104ddecf4d39831609e0cc5957e2/artifacts
end_time: 1763497993574
entry_point_name: ''
experiment_id: '960079160078124089'
lifecycle_stage: active
run_id: bd66104ddecf4d39831609e0cc5957e2
run_name: xgboost
source_name: ''
source_type: 4
source_version: ''
start_time: 1763497990202
status: 3
tags: []
user_id: redsk
