artifact_uri: file:///C:/CMU%20Projects/Operationalizing%20AI/rt_crypto_volatility/mlruns/960079160078124089/b89ca033c6cc4c8592ff3a1bedb0bc1e/artifacts
end_time: 1763500705749
entry_point_name: ''
experiment_id: '960079160078124089'
lifecycle_stage: active
run_id: b89ca033c6cc4c8592ff3a1bedb0bc1e
run_name: xgboost
source_name: ''
source_type: 4
source_version: ''
start_time: 1763500700416
status: 3
tags: []
user_id: redsk
