artifact_uri: file:///C:/CMU%20Projects/Operationalizing%20AI/rt_crypto_volatility/mlruns/875896030304522619/4e8324b43b20447caa25fbe5b3dcb665/artifacts
end_time: 1763562655150
entry_point_name: ''
experiment_id: '875896030304522619'
lifecycle_stage: active
run_id: 4e8324b43b20447caa25fbe5b3dcb665
run_name: lr_tune_2
source_name: ''
source_type: 4
source_version: ''
start_time: 1763562655107
status: 3
tags: []
user_id: redsk
