artifact_location: file:///C:/CMU%20Projects/Operationalizing%20AI/rt_crypto_volatility/mlruns/960079160078124089/models/m-1c1b08bf6ae04a40b0d7195f69a32148/artifacts
creation_timestamp: 1763500990595
experiment_id: '960079160078124089'
last_updated_timestamp: 1763500993124
model_id: m-1c1b08bf6ae04a40b0d7195f69a32148
model_type: null
name: model
source_run_id: 5fb5aa0865fe4348b9c657a68732240c
status: 2
status_message: null
