artifact_uri: file:///C:/CMU%20Projects/Operationalizing%20AI/rt_crypto_volatility/mlruns/960079160078124089/de2dd10c0eae445d8319b48457585581/artifacts
end_time: 1763512581398
entry_point_name: ''
experiment_id: '960079160078124089'
lifecycle_stage: active
run_id: de2dd10c0eae445d8319b48457585581
run_name: logistic_regression
source_name: ''
source_type: 4
source_version: ''
start_time: 1763512572034
status: 3
tags: []
user_id: redsk
