artifact_uri: file:///C:/CMU%20Projects/Operationalizing%20AI/rt_crypto_volatility/mlruns/960079160078124089/21eff4509e7d476784d250b3e70919c9/artifacts
end_time: 1763508883173
entry_point_name: ''
experiment_id: '960079160078124089'
lifecycle_stage: active
run_id: 21eff4509e7d476784d250b3e70919c9
run_name: xgboost
source_name: ''
source_type: 4
source_version: ''
start_time: 1763508880513
status: 3
tags: []
user_id: redsk
