artifact_uri: file:///C:/CMU%20Projects/Operationalizing%20AI/rt_crypto_volatility/mlruns/960079160078124089/3a1378366be8431e8a6ca72c0c6070f4/artifacts
end_time: 1763499730626
entry_point_name: ''
experiment_id: '960079160078124089'
lifecycle_stage: active
run_id: 3a1378366be8431e8a6ca72c0c6070f4
run_name: baseline_zscore
source_name: ''
source_type: 4
source_version: ''
start_time: 1763499730516
status: 3
tags: []
user_id: redsk
