artifact_uri: file:///C:/CMU%20Projects/Operationalizing%20AI/rt_crypto_volatility/mlruns/960079160078124089/26ae042996b347f78595f09e5ba96294/artifacts
end_time: 1763500700414
entry_point_name: ''
experiment_id: '960079160078124089'
lifecycle_stage: active
run_id: 26ae042996b347f78595f09e5ba96294
run_name: logistic_regression
source_name: ''
source_type: 4
source_version: ''
start_time: 1763500405148
status: 3
tags: []
user_id: redsk
