artifact_uri: file:///C:/CMU%20Projects/Operationalizing%20AI/rt_crypto_volatility/mlruns/960079160078124089/d0fc867c297448ba9ff4aecad2625223/artifacts
end_time: 1763512354178
entry_point_name: ''
experiment_id: '960079160078124089'
lifecycle_stage: active
run_id: d0fc867c297448ba9ff4aecad2625223
run_name: xgboost
source_name: ''
source_type: 4
source_version: ''
start_time: 1763512351391
status: 3
tags: []
user_id: redsk
