artifact_location: file:///C:/CMU%20Projects/Operationalizing%20AI/rt_crypto_volatility/mlruns/960079160078124089/models/m-520cc339c95b4dd88c19fed0f1cf1b66/artifacts
creation_timestamp: 1763501036177
experiment_id: '960079160078124089'
last_updated_timestamp: 1763501038755
model_id: m-520cc339c95b4dd88c19fed0f1cf1b66
model_type: null
name: model
source_run_id: 71bb54efedcf491d99475a0ae48408ff
status: 2
status_message: null
