artifact_uri: file:///C:/CMU%20Projects/Operationalizing%20AI/rt_crypto_volatility/mlruns/960079160078124089/f1792009f83e4a6a8b56afa2dde6c294/artifacts
end_time: 1763497963865
entry_point_name: ''
experiment_id: '960079160078124089'
lifecycle_stage: active
run_id: f1792009f83e4a6a8b56afa2dde6c294
run_name: baseline_zscore
source_name: ''
source_type: 4
source_version: ''
start_time: 1763497963759
status: 3
tags: []
user_id: redsk
